# Generated by Django 2.0.4 on 2018-04-10 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_comment_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
